version: '3.7'

services:

    angular:
      build: docker/images/angular
      image: ${APP_NAME}-angular:develop
      tty: true
      volumes:
        - .:/var/www/app
      ports:
          - "4200:4200"
          - "4201:4201"
      working_dir: /var/www/app/application
